---
logging:
  level:
    root: WARN
    org.springframework.security: INFO
    oidc: DEBUG
  threshold:
    console: WARN

server:
  port: 8881
  error:
    path: "/error"
    include-message: always
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: false

spring:
  main:
    banner-mode: "off"
  mvc:
    log-request-details: false
  security:
    oauth2:
      client:
        registration:
          oidcng:
            client-id: playground_client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"
            scope: openid
        provider:
          oidcng:
            authorization-uri: "https://connect.test2.surfconext.nl/oidc/authorize"
            token-uri: "https://connect.test2.surfconext.nl/oidc/token"
            user-info-uri: "https://connect.test2.surfconext.nl/oidc/userinfo"
            jwk-set-uri: "https://connect.test2.surfconext.nl/oidc/certs"
            user-name-attribute: sub
            user-info-authentication-method: client_secret_basic
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    git:
      mode: full

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
